### ISSUE TITLE
DEBUG - The file did not specify the _Valid column attribute

### ISSUE THREAD

**Issue by k3yavi** [velocyto-team/velocyto-notebooks#2]
Hi,
I used command `velocyto run10x` command to create the `.loom` file on a 10x data, but when I tried reading the `loom` file in `ipyton-notebook` I get the above error. Any pointer please?
I used the following command in ipython
```
vlm = vcy.VelocytoLoom("mouse.loom")
```

Thanks in advance.

**Comment by gioelelm** [comment]
It is not an error. It is a warning, isn't it? Notice there is not traceback and it is labelled DEBUG not Error. Anyways thanks for making me notice that, it is some left over code from an older version and is nonsensical now. I will remove it in the next release.

**Comment by k3yavi** [comment]
thanks @gioelelm for such a quick reply.
You are right, It might be the warning. 
I am new to the `loom` data-structure and got confused since when I run next set of lines in [this](https://github.com/velocyto-team/velocyto-notebooks/blob/master/python/DentateGyrus.ipynb) notebook I get following error:
```
KeyError: 'TSNE1'
```
the command I used were
```
vlm = vcy.VelocytoLoom("mouse.loom")
vlm.ts = np.column_stack([vlm.ca["TSNE1"], vlm.ca["TSNE2"]])
```

Basically the question is does the loom file should always contain the `TSNE1` information? if yes, then I might not be creating the right `loom` file or I am not importing it in the right way which let to my first question.
Hope it makes sense.

**Comment by gioelelm** [comment]
No it does not have to contain it. In the notebook example that line was just a shortcut to spare users from recalculatint the TSNE (that can be quite time consuming). In this case, you are supposed to calculate the embedding yourself. 

I suggest consulting the [loompy documentation](http://linnarssonlab.org/loompy/) to become more familiar with the loom format. But after all is nothing particularly exoteric, is pretty much a dataframe stored in a efficient way. 

Furthermore since the loom file creation went through without errors there is no reason to believe that something went wrong in that step. maybe check the columns and row sums to diagnose possible failures, but I would guess everything should be normal.

**Comment by k3yavi** [comment]
Thanks @gioelelm , closing the issue !
