### ISSUE TITLE
No velocity arrows showing up

### ISSUE THREAD

**Issue by k3yavi** [velocyto-team/velocyto-notebooks#3]
Hi, I am trying to run `velocyto` on 10x data using the following set of commands.
```
vlm = vcy.VelocytoLoom("mouse.loom")
colors_dict = {0: np.array([ 0.95,  0.6,  0.1]), 1: np.array([ 0.85,  0.3,  0.1]), 2: np.array([ 0.8,  0.02,  0.1]),
              3: np.array([ 0.81,  0.43,  0.72352941]), 4: np.array([ 0.61,  0.13,  0.72352941]), 5: np.array([ 0.9,  0.8 ,  0.3])}
vlm.set_clusters(vlm.ca["Clusters"], cluster_colors_dict=colors_dict)
vlm.normalize("S", size=True, log=True)
vlm.normalize("U", size=True, log=True)
vlm.default_filter_and_norm()
vlm.default_fit_preparation()
vlm.fit_gammas()
vlm.predict_U()
vlm.calculate_velocity()
vlm.calculate_shift(assumption="constant_velocity")
vlm.extrapolate_cell_at_t(delta_t=1)
vlm.perform_TSNE()
vlm.estimate_transition_prob(hidim="Sx_sz", embed="ts", transform="linear")
vlm.calculate_embedding_shift(sigma_corr = 0.05)
vlm.calculate_grid_arrows(smooth=0.8, steps=(20, 20), n_neighbors=50)
vlm.plot_grid_arrows(scatter_kwargs_dict={"alpha":0.35, "lw":0.35, "edgecolor":"0.4", "s":38, "rasterized":True}, min_mass=24, angles='xy', scale_units='xy', headaxislength=2.75, headlength=5, headwidth=4.8, quiver_scale=0.47)
```
Note: I have to change the `transform` parameter of function `vlm.estimate_transition_prob` to `linear` since `sqrt` was giving error. 

Also attaching the log of the run which gives some divide by 0 warning.
At the end I am just getting the PCA colored plot of the cells without any flow (arrow), what am I missing?
[log.txt](https://github.com/velocyto-team/velocyto-notebooks/files/1776616/log.txt)

Thanks again!

**Comment by gioelelm** [comment]
The problems of your analysis are:
(1) that you are ending up with few cells with zero unspliced molecules (a symptom  of the fact that the gene filtering is too strong for your type of data)
(2) You are using a linear transform to estimate transition probability, this is not always wrong but it assumes an extremely good feature selection and an appropriate scaling of the gene expression of the genes taken in consideration. In general sqrt or log are a much better idea
(3) Last but not least, the velocity representation provided by plot_grid_arrows can be only relative so you are probably in a regime of plotting parameters where the signal is too small.
Try ( ~ in order of importance): 
decrese `min_mass` (how much will depend from smooth and N_cells) up to the point where you see dots or arrows only in points above your cloud of points. 
increase `sigma_corr`
decrease `smooth`
increse `steps`
increse/decrese `n_neighbors `to  ~ N_cells / steps[0]

I'd like to remind you that velocyto is an alpha version and analysing data using velocyto (as any other bioinformatic tool) should be be carried on trying to understand the implication of each step. Only because we are packaging a whole single cell analysis as 10-liner does not mean the default values will work. 
Anyways this is probably my fault: I should have removed the "default*" functions (or maybe calling them "naive*" or "heuristic*") because many people fall in the same mistake of thinking that those function are a panacea and use them as they are while the are just example functions (as I explain in the docs). So the right way to use them would be to choose carefully its parameters and eventually read the source code and implement a final filtering, normalisation scheme that fits best your dataset.

**Comment by k3yavi** [comment]
Thanks @gioelelm for such a quick response.
I guess I am at fault too for not reading the docs properly and trying to just run the default pipeline. I'll test the variations you suggested and ping you back again if you don't mind; for now closing the issue.
Thanks again for such an awesome preprint and tool, it's really a pleasure reading it.
